#
# 1. https://hub.docker.com/r/powerdns/dnsdist-19
---

#version: '3'

networks:
  traefik-proxy:
    driver: overlay
    attachable: true
    external: true

volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fs1-san.home,rw,nolock,soft
      device: :/mnt/fs1/Applications

services:
  dnsdist:
    hostname: "dnsdist-1"
    image: "powerdns/dnsdist-19:1.9.6"
    restart: unless-stopped
    tty: true
    user: "pdns:pdns" # 953:953
    stdin_open: true
    #command: ["--disable-syslog", "--uid", "pdns", "--gid", "pdns", "--verbose", "--check-config"]
    command: ["--disable-syslog", "--uid", "pdns", "--gid", "pdns", "--verbose"]
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "./mounts/config/conf.d/_api.conf:/etc/dnsdist/conf.d/_api.conf:rw"
      - "./mounts/config/conf.d:/etc/dnsdist/conf.d:ro"
      - "./mounts/config/dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro"
      - "./mounts/logs/dnsdist.log:/var/log/dnsdist.log:rw"
      #- config:/test:rw
      - "./mounts/ssl/ca.pem:/etc/ssl/ca.pem:ro"
      - "./mounts/ssl/tls.pem:/etc/ssl/tls.pem:ro"
      - "./mounts/ssl/tls.key:/etc/ssl/tls.key:ro"
    environment:
      - TZ=America/Chicago
      - LC_TIME=C.UTF-8
      - LANG=en_US.UTF-8
    env_file:
      - "./.env.secrets"
    ports:
      # DNS over HTTP(S); dns-doh
      - "433:443"
      # DNS over TLS; dns-tls
      - "853:853" # tcp
      # unencrypted DNS TCP; dns-tcp
      - "53:53/tcp"
      # DEPRECATED(JEFF): The UDP endpoint should never be used
      # for new setups as it will some day be removed -- the TCP
      # endpoint should always be used instead.
      # unencrypted DNS UDP; dns-udp
      - "53:53/udp"
      # webserver; dns-web
      - "8083:8083"
      # console; dns-console
      - "5199:5199"
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      # dnsdist webserver endpoint
      - "traefik.http.routers.dnsdist.entrypoints=web"
      - "traefik.http.routers.dnsdist.rule=Host(`logs.dnsdist.fs1.home`) && PathPrefix(`/`)"
      - "traefik.http.services.dnsdist.loadbalancer.server.port=8083"
      - "traefik.http.routers.dnsdist.tls.certresolver=staging-web-acme"
      - "traefik.http.routers.dnsdist.service=dnsdist"
      # dnsdist console
      - "traefik.http.routers.console.entrypoints=web"
      - "traefik.http.routers.console.rule=Host(`console.dnsdist.fs1.home`) && PathPrefix(`/`)"
      - "traefik.http.services.console.loadbalancer.server.port=5199"
      - "traefik.http.routers.console.tls.certresolver=staging-web-acme"
      - "traefik.http.routers.console.service=console"
      # dns-tcp
      - "traefik.tcp.routers.dns-tcp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.dns-tcp.entrypoints=dns-tcp"
      - "traefik.tcp.services.dns-tcp.loadbalancer.server.port=53"
      - "traefik.tcp.routers.dns-tcp.service=dns-tcp"
      # dns-doh
      - "traefik.tcp.routers.dns-doh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.dns-doh.entrypoints=dns-doh"
      - "traefik.tcp.services.dns-doh.loadbalancer.server.port=433"
      - "traefik.tcp.routers.dns-doh.service=dns-doh"
      # dns-tls
      - "traefik.tcp.routers.dns-tls.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.dns-tls.entrypoints=dns-tls"
      - "traefik.tcp.services.dns-tls.loadbalancer.server.port=853"
      - "traefik.tcp.routers.dns-tls.service=dns-tls"
      #
      - "homepage.group=syn"
      - "homepage.name=dnsdist"
      - "homepage.siteMonitor=http://docker.fs1.home:8083/"
      #- "homepage.siteMonitor=https://dnsdist.fs1.home"
      - "homepage.ping=docker.fs1.home"
