#
# 1. https://hub.docker.com/r/powerdns/dnsdist-19
---

#version: '3'

networks:
  traefik-proxy:
    driver: overlay
    attachable: true
    external: true

volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fs1-san.home,rw,nolock,soft
      device: :/mnt/fs1/Applications

services:
  dnsdist:
    hostname: "dnsdist-1"
    image: "powerdns/dnsdist-19:1.9.6"
    restart: "on-failure:2"
    tty: true
    stdin_open: true
    #command: ["/etc/dnsdist/entrypoint.sh"]
    command: ["--disable-syslog", "--uid", "pdns", "--gid", "pdns", "--verbose"]
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./mounts/config/conf.d:/etc/dnsdist/conf.d:ro"
      - "./mounts/config/dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro"
      - "./mounts/config/entrypoint.sh:/etc/dnsdist/entrypoint.sh:ro"
      # FIXME(JEFF): permission denied error -- as the pdns user inside the container
      #- "./mounts/logs/dnsdist.log:/var/log/dnsdist.log:rw"
      #- config:/test:rw
    environment:
      - TZ=America/Chicago
      - LC_TIME=C.UTF-8
      - LANG=en_US.UTF-8
    env_file:
      - "./.env.secrets"
    ports:
      # DNS over HTTP(S)
      - "8053:8053"
      # DNS over TLS
      - "853:853"
      # unencrypted DNS TCP
      - "53:53"
      # unencrypted DNS UDP
      - "53:53/udp"
      # webserver
      - "127.0.0.1:8081:8081"
    networks:
      - traefik-proxy

