#
# 1. https://hub.docker.com/r/powerdns/dnsdist-19
---

#version: '3'

networks:
  traefik-proxy:
    driver: overlay
    attachable: true
    external: true

volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fs1-san.home,rw,nolock,soft
      device: :/mnt/fs1/Applications

services:
  dnsdist:
    hostname: "dnsdist-1"
    image: "powerdns/dnsdist-19:1.9.6"
    restart: unless-stopped
    tty: true
    user: "pdns:pdns" # 953:953
    stdin_open: true
    #command: ["--disable-syslog", "--uid", "pdns", "--gid", "pdns", "--verbose", "--check-config"]
    command: ["--disable-syslog", "--uid", "pdns", "--gid", "pdns", "--verbose"]
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./mounts/config/conf.d/_api.conf:/etc/dnsdist/conf.d/_api.conf:rw"
      - "./mounts/config/conf.d:/etc/dnsdist/conf.d:ro"
      - "./mounts/config/dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro"
      - "./mounts/logs/dnsdist.log:/var/log/dnsdist.log:rw"
      #- config:/test:rw
    environment:
      - TZ=America/Chicago
      - LC_TIME=C.UTF-8
      - LANG=en_US.UTF-8
    env_file:
      - "./.env.secrets"
    ports:
      # DNS over HTTP(S)
      - "8053:8053"
      # DNS over TLS
      - "853:853"
      # unencrypted DNS TCP
      - "53:53"
      # unencrypted DNS UDP
      - "53:53/udp"
      # webserver
      - "8083:8083"
      #- "127.0.0.1:8083:8083"
      # console
      - "127.0.0.1:5199:5199"
    networks:
      - traefik-proxy
    labels:
      - "homepage.group=syn"
      - "homepage.name=dnsdist-1"
      - "homepage.siteMonitor=http://docker.fs1.home:8083"
      - "homepage.ping=docker.fs1.home"

