#
# 1. https://hub.docker.com/r/powerdns/dnsdist-19
---
version: '3'

services:
  dnsdist:
    hostname: "dnsdist-1"
    image: "powerdns/dnsdist-19:1.9.6"
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: ["--disable-syslog", "--uid", "dnsdist", "--gid", "dnsdist", "--verbose"]
    volumes:
      - ./mounts/dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro
    ports:
      - 8053:8053 # DNS over HTTP(S)
      - 853:853 # DNS over TLS
      - 53:53 # unencrypted DNS TCP
      - 53:53/udp # unencrypted DNS UDP
